# -*- coding: utf-8 -*-
from tenant_api.serializers.associate_operations.associate_avatar_create_or_update import AssociateAvatarCreateOrUpdateSerializer
from tenant_api.serializers.associate_operations.associate_balance_operation import AssociateBalanceOperationSerializer
from tenant_api.serializers.associate_operations.associate_password_operation import AssociateChangePasswordOperationSerializer
from tenant_api.serializers.associate_operations.associate_upgrade_operation import AssociateUpgradeOperationSerializer
from tenant_api.serializers.associate_operations.associate_downgrade_operation import AssociateDowngradeOperationSerializer
