from tenant_api.serializers.order_crud.order_lite_update import WorkOrderLiteUpdateSerializer
from tenant_api.serializers.order_crud.order_financial_update import WorkOrderFinancialUpdateSerializer

from tenant_api.serializers.order_crud.ongoing_order_comment import OngoingWorkOrderCommentListCreateSerializer

from tenant_api.serializers.order_crud.v2_ongoing_order_retrieve import OngoingWorkOrderRetrieveSerializer
from tenant_api.serializers.order_crud.v2_ongoing_order_update import OngoingWorkOrderUpdateSerializer

from tenant_api.serializers.order_crud.order_file_upload import WorkOrderFileUploadListCreateSerializer

from tenant_api.serializers.order_crud.invoice_retrieve import WorkOrderInvoiceRetrieveSerializer

from tenant_api.serializers.order_crud.invoice_first_section_update import WorkOrderInvoiceFirstSectionUpdateSerializer
from tenant_api.serializers.order_crud.invoice_second_section_update import WorkOrderInvoiceSecondSectionUpdateSerializer
from tenant_api.serializers.order_crud.invoice_third_section_update import WorkOrderInvoiceThirdSectionUpdateSerializer

from tenant_api.serializers.order_crud.deposit_list_create import WorkOrderDepositListCreateSerializer
from tenant_api.serializers.order_crud.deposit_retrieve_delete import WorkOrderDepositRetrieveDeleteSerializer
