# -*- coding: utf-8 -*-
from tenant_api.serializers.customer_crud.customer_list_create import CustomerListCreateSerializer
from tenant_api.serializers.customer_crud.customer_contact_update import CustomerContactUpdateSerializer
from tenant_api.serializers.customer_crud.customer_address_update import CustomerAddressUpdateSerializer
from tenant_api.serializers.customer_crud.customer_metrics_update import CustomerMetricsUpdateSerializer
from tenant_api.serializers.customer_crud.customer_retrieve_update import CustomerRetrieveUpdateDestroySerializer
