# -*- coding: utf-8 -*-
from tenant_api.views.task_operation.assign_associate import AssignAssociateTaskOperationAPIView
from tenant_api.views.task_operation.follow_up import FollowUpTaskOperationAPIView # DEPRECATED
from tenant_api.views.task_operation.follow_up_pending import FollowUpPendingTaskOperationAPIView # DEPRECATED
from tenant_api.views.task_operation.close import CloseTaskOperationAPIView
from tenant_api.views.task_operation.v2_follow_up_pending import FollowUpPendingTaskOperationV2APIView
from tenant_api.views.task_operation.v2_follow_up import FollowUpTaskOperationV2APIView
from tenant_api.views.task_operation.order_completion import OrderCompletionTaskOperationAPIView
from tenant_api.views.task_operation.survey import SurveyTaskOperationAPIView
