# Generated by Django 2.0.5 on 2018-06-03 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tenant_foundation.models.public_image_upload
import workery.s3utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicImageUpload',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.public_image_upload.increment_public_image_upload_id_number, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(help_text='The upload image.', storage=workery.s3utils.PublicMediaStorage(), upload_to='uploads/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this away log.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_publicimageupload_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom last modified this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_publicimageupload_last_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Image Upload',
                'verbose_name_plural': 'Public Image Uploads',
                'db_table': 'workery_public_image_uploads',
                'permissions': (('can_get_public_image_uploads', 'Can get public image uploads'), ('can_get_public_image_upload', 'Can get public image upload'), ('can_post_public_image_upload', 'Can create public image upload'), ('can_put_public_image_upload', 'Can update public image upload'), ('can_delete_public_image_upload', 'Can delete public image upload')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='associate',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this associate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_associate_avatar_image_related', to='tenant_foundation.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_customer_avatar_image_related', to='tenant_foundation.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='organization',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_organization_avatar_image_related', to='tenant_foundation.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='partner',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this partner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_partner_avatar_image_related', to='tenant_foundation.PublicImageUpload'),
        ),
        migrations.AddField(
            model_name='staff',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_staff_avatar_image_related', to='tenant_foundation.PublicImageUpload'),
        ),
    ]
