# Generated by Django 2.0.5 on 2018-06-28 02:55

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='state',
            field=django_fsm.FSMField(blank=True, db_index=True, default='new', help_text='The state of this job order.', max_length=50, verbose_name='State'),
        ),
    ]
