# Generated by Django 2.0.5 on 2018-06-03 15:46

from django.db import migrations
import sorl.thumbnail.fields
import workery.s3utils


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicimageupload',
            name='image_file',
            field=sorl.thumbnail.fields.ImageField(help_text='The upload image.', storage=workery.s3utils.PublicMediaStorage(), upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
