# Generated by Django 2.0.5 on 2018-05-26 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='hourly_salary_desired',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The hourly salary rate the associate', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Hourly Salary Desired'),
        ),
    ]
