# Generated by Django 2.0.5 on 2018-06-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='invoice_id',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Residential Job Type'), (2, 'Commercial Job Type'), (3, 'Unassigned Job Type')], default=3, help_text='The type of job this is.', verbose_name='Invoice ID'),
        ),
    ]
