# Generated by Django 2.0.4 on 2018-05-19 21:43

from django.db import migrations, models
import tenant_foundation.models.insurance_requirement


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRequirement',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.insurance_requirement.increment_insurance_requirement_id_number, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, help_text='The text content of this insurance_requirement.', max_length=31, unique=True, verbose_name='Text')),
                ('description', models.TextField(blank=True, default='', help_text='A short description of this insurance_requirement.', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Insurance Requirement',
                'verbose_name_plural': 'Insurance Requirements',
                'db_table': 'workery_insurance_requirements',
                'permissions': (('can_get_insurance_requirements', 'Can get insurance_requirements'), ('can_get_insurance_requirement', 'Can get insurance_requirement'), ('can_post_insurance_requirement', 'Can create insurance_requirement'), ('can_put_insurance_requirement', 'Can update insurance_requirement'), ('can_delete_insurance_requirement', 'Can delete insurance_requirement')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='associate',
            name='insurance_requirements',
            field=models.ManyToManyField(blank=True, help_text='The insurance requirements this associate meets.', related_name='tenant_foundation_associate_insurance_requirements_related', to='tenant_foundation.InsuranceRequirement'),
        ),
    ]
