# Generated by Django 2.0.5 on 2018-06-15 02:27

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_workorder_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='is_cancelled',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='state',
            field=django_fsm.FSMField(blank=True, db_index=True, default='pending', help_text='The state of this job order.', max_length=50, verbose_name='State'),
        ),
    ]
