# Generated by Django 2.0.5 on 2018-06-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20180615_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='drivers_license_class',
            field=models.CharField(blank=True, help_text='The associates license class for driving.', max_length=31, null=True, verbose_name='Divers License Class'),
        ),
    ]
