# Generated by Django 2.0.4 on 2018-05-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20180520_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservicefee',
            name='description',
            field=models.TextField(help_text='A short description of this service fee.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='orderservicefee',
            name='percentage',
            field=models.FloatField(blank=True, default=0, help_text='The percent to take from job orders', verbose_name='Percent'),
        ),
        migrations.AlterField(
            model_name='orderservicefee',
            name='title',
            field=models.CharField(help_text='The official title of this service.', max_length=63, verbose_name='Title'),
        ),
    ]
