# Generated by Django 2.0.5 on 2018-05-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20180526_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether comment was archived.', verbose_name='Is Archived'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='other_telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone the alternative telephone is. Ex: work, home, etc.', verbose_name='Other telephone type of'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone this is. Ex: work, home, etc.', verbose_name='Telephone type of'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='other_telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone the alternative telephone is. Ex: work, home, etc.', verbose_name='Other telephone type of'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone this is. Ex: work, home, etc.', verbose_name='Telephone type of'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='other_telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone the alternative telephone is. Ex: work, home, etc.', verbose_name='Other telephone type of'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone this is. Ex: work, home, etc.', verbose_name='Telephone type of'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='other_telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone the alternative telephone is. Ex: work, home, etc.', verbose_name='Other telephone type of'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone this is. Ex: work, home, etc.', verbose_name='Telephone type of'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='other_telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone the alternative telephone is. Ex: work, home, etc.', verbose_name='Other telephone type of'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone this is. Ex: work, home, etc.', verbose_name='Telephone type of'),
        ),
    ]
