# Generated by Django 2.0.4 on 2018-05-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20180520_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='invoice_service_fee_by_franchise',
            new_name='invoice_service_fee',
        ),
    ]
