# Generated by Django 2.0.5 on 2018-06-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_activitysheetitem_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysheetitem',
            name='has_accepted_job',
        ),
    ]
