# Generated by Django 2.0.5 on 2018-06-30 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_remove_activitysheetitem_has_accepted_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaylog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_awaylog_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_comment_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicimageupload',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_publicimageupload_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_taskitem_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_workorder_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='latest_pending_task',
            field=models.ForeignKey(blank=True, help_text='The latest pending task of our job order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_workorder_latest_pending_task_related', to='tenant_foundation.TaskItem'),
        ),
        migrations.AlterField(
            model_name='workorderservicefee',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_workorderservicefee_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
