# Generated by Django 2.0.5 on 2018-07-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0005_auto_20180630_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Assign associate'), (2, 'Follow up is job complete'), (3, 'Follow up customer survey'), (4, 'Follow up did associate accept job')], help_text='The type of task item this is.', verbose_name='Type of'),
        ),
    ]
