# Generated by Django 2.0.5 on 2018-07-08 01:01

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import tenant_foundation.models.ongoing_work_order


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_auto_20180705_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingWorkOrder',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.ongoing_work_order.increment_order_id_number, editable=False, primary_key=True, serialize=False)),
                ('state', django_fsm.FSMField(blank=True, db_index=True, default='idle', help_text='The state of this ongoing work order.', max_length=50, verbose_name='State')),
                ('associate', models.ForeignKey(blank=True, help_text='The associate of our ongoing work order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_ongoingworkorder_associate_related', to='tenant_foundation.Associate')),
                ('closed_orders', models.ManyToManyField(blank=True, help_text='The work orders associated with this ongoing work order.', related_name='tenant_foundation_ongoingworkorder_closed_orders_related', to='tenant_foundation.WorkOrder')),
                ('customer', models.ForeignKey(help_text='The customer of our ongoing work order.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_ongoingworkorder_customer_related', to='tenant_foundation.Customer')),
                ('open_order', models.ForeignKey(blank=True, help_text='The work order which is currently running for this ongoing work order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_ongoingworkorder_open_order_related', to='tenant_foundation.WorkOrder')),
            ],
            options={
                'verbose_name': 'Ongoing Work Order',
                'verbose_name_plural': 'Ongoing Work Orders',
                'db_table': 'workery_ongoing_work_orders',
                'permissions': (('can_get_orders', 'Can get work orders'), ('can_get_order', 'Can get work order'), ('can_post_order', 'Can create work order'), ('can_put_order', 'Can update work order'), ('can_delete_order', 'Can delete work order')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='ongoing_work_order',
            field=models.ForeignKey(blank=True, help_text='The ongoing work order that this work order is a part of.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_workorder_ongoing_work_order_related', to='tenant_foundation.OngoingWorkOrder'),
        ),
    ]
