# Generated by Django 2.0.4 on 2018-05-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_auto_20180521_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_fee_currency',
        ),
    ]
