# Generated by Django 2.0.4 on 2018-05-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0007_auto_20180521_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_service_fee_payment_date',
            field=models.DateField(blank=True, help_text='The date when the service fee was paid by the associate.', null=True, verbose_name='Invoice Service Fee Payment Date'),
        ),
    ]
