# Generated by Django 2.0.5 on 2018-07-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0007_auto_20180708_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='how_hear_other',
            field=models.CharField(blank=True, help_text='How customer heared/learned about this Over 55 Inc.', max_length=2055, null=True, verbose_name='Learned about us (other)'),
        ),
    ]
