# Generated by Django 2.0.4 on 2018-05-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0008_order_invoice_service_fee_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_service_fee_payment_date',
            field=models.DateField(blank=True, db_index=True, help_text='The date when the service fee was paid by the associate.', null=True, verbose_name='Invoice Service Fee Payment Date'),
        ),
    ]
