# Generated by Django 2.0.4 on 2018-05-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0009_auto_20180521_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_date',
        ),
    ]
