# Generated by Django 2.0.5 on 2018-07-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0009_auto_20180723_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='join_date',
            field=models.DateField(blank=True, help_text='The date the customer joined this organization.', null=True, verbose_name='Join Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateField(blank=True, help_text='The date the customer joined this organization.', null=True, verbose_name='Join Date'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='join_date',
            field=models.DateField(blank=True, help_text='The date the customer joined this organization.', null=True, verbose_name='Join Date'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateField(blank=True, help_text='The date the customer joined this organization.', null=True, verbose_name='Join Date'),
        ),
    ]
