# Generated by Django 2.0.7 on 2018-07-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0010_auto_20180725_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_blacklisted',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether customer was blacklisted or not.', verbose_name='Is Blacklisted'),
        ),
    ]
