# Generated by Django 2.0.7 on 2018-07-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0011_customer_is_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingworkorder',
            name='latest_pending_task',
            field=models.ForeignKey(blank=True, help_text='The latest pending task of our ongoing job order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_ongoingworkorder_latest_pending_task_task_related', to='tenant_foundation.TaskItem'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Assign associate'), (2, 'Follow up is job complete'), (3, 'Follow up customer survey'), (4, 'Follow up did associate accept job'), (5, 'Follow up was ongoing job updated')], help_text='The type of task item this is.', verbose_name='Type of'),
        ),
    ]
