# Generated by Django 2.0.4 on 2018-05-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0011_auto_20180521_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether associate was archived.', verbose_name='Is Archived'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(help_text='The organization that this customer is affiliated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_foundation.Organization'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether order was archived.', verbose_name='Is Archived'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether partner was archived.', verbose_name='Is Archived'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether staff was archived.', verbose_name='Is Archived'),
        ),
    ]
