# Generated by Django 2.0.7 on 2018-07-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0013_auto_20180729_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysheetitem',
            name='ongoing_job',
            field=models.ForeignKey(blank=True, help_text='The ongoing job associated with thie activity sheet item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_activitysheetitem_ongoing_work_order_related', to='tenant_foundation.OngoingWorkOrder'),
        ),
        migrations.AlterField(
            model_name='activitysheetitem',
            name='job',
            field=models.ForeignKey(blank=True, help_text='The job associated with thie activity sheet item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_activitysheetitem_work_order_related', to='tenant_foundation.WorkOrder'),
        ),
    ]
