# Generated by Django 2.0.7 on 2018-08-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0016_auto_20180808_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='was_survey_conducted',
            field=models.BooleanField(default=False, help_text='Track whether survey was conducted post completion (if completed).', verbose_name='Was Survey Conducted'),
        ),
    ]
