# Generated by Django 2.0.7 on 2018-08-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0017_workorder_was_survey_conducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='was_there_financials_inputted',
            field=models.BooleanField(default=True, help_text='Track whether financials where inputted.', verbose_name='Was there financials inputted?'),
        ),
    ]
