# Generated by Django 2.0.7 on 2018-08-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0019_associate_wsib_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='wsib_number',
            field=models.CharField(blank=True, help_text='Assigned WSIB number to this associate.', max_length=127, null=True, verbose_name='WSIB #'),
        ),
    ]
