# Generated by Django 2.0.7 on 2018-08-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0020_auto_20180824_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingworkorder',
            name='frequency',
            field=models.CharField(blank=True, help_text='The frequency of the ongoing job.', max_length=31, null=True, verbose_name='Frequency'),
        ),
    ]
