# Generated by Django 2.0.7 on 2018-08-31 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0022_ongoingworkorder_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='follow_up_days_number',
        ),
    ]
