# Generated by Django 2.0.7 on 2018-09-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0023_remove_workorder_follow_up_days_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='category',
            field=models.CharField(db_index=True, help_text='The category text of this skill set.', max_length=127, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='sub_category',
            field=models.CharField(db_index=True, help_text='The sub-category text of this skill set.', max_length=127, verbose_name='Sub-Category'),
        ),
    ]
