# Generated by Django 2.0.9 on 2019-01-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0027_auto_20181123_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='awaylog',
            name='start_date',
            field=models.DateField(blank=True, help_text='The date that this user will start their absence on.', null=True, verbose_name='Away start date'),
        ),
    ]
