# Generated by Django 2.0.9 on 2019-01-22 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0028_awaylog_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='assignment_date',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='associate',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='closed_orders',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='is_home_support_service',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='latest_pending_task',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='skill_sets',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='ongoingworkorder',
            name='type_of',
        ),
        migrations.AlterField(
            model_name='activitysheetitem',
            name='associate',
            field=models.ForeignKey(help_text='The associate with this activity sheet item.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_sheet_items', to='tenant_foundation.Associate'),
        ),
        migrations.AlterField(
            model_name='activitysheetitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this activity sheet item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activity_sheet_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitysheetitem',
            name='job',
            field=models.ForeignKey(blank=True, help_text='The job associated with thie activity sheet item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_sheet_items', to='tenant_foundation.WorkOrder'),
        ),
        migrations.AlterField(
            model_name='activitysheetitem',
            name='ongoing_job',
            field=models.ForeignKey(blank=True, help_text='The ongoing job associated with thie activity sheet item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_sheet_items', to='tenant_foundation.OngoingWorkOrder'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this associate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associates', to='tenant_foundation.PublicImageUpload'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='away_log',
            field=models.ForeignKey(blank=True, help_text='The object referencing our Assocaites away log (if they have one).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associates', to='tenant_foundation.AwayLog'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_associates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='associate',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_associates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='associatecomment',
            name='about',
            field=models.ForeignKey(help_text='The associate whom this comment is about.', on_delete=django.db.models.deletion.CASCADE, related_name='associate_comments', to='tenant_foundation.Associate'),
        ),
        migrations.AlterField(
            model_name='associatecomment',
            name='comment',
            field=models.ForeignKey(help_text='The comment this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='associate_comments', to='tenant_foundation.Comment'),
        ),
        migrations.AlterField(
            model_name='awaylog',
            name='associate',
            field=models.ForeignKey(help_text='The associate of our away log.', on_delete=django.db.models.deletion.CASCADE, related_name='away_logs', to='tenant_foundation.Associate'),
        ),
        migrations.AlterField(
            model_name='awaylog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_away_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='awaylog',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom last modified this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_away_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom last modified this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='tenant_foundation.PublicImageUpload'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(help_text='The organization that this customer is affiliated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='tenant_foundation.Organization'),
        ),
        migrations.AlterField(
            model_name='customercomment',
            name='about',
            field=models.ForeignKey(help_text='The customer whom this comment is about.', on_delete=django.db.models.deletion.CASCADE, related_name='customer_comments', to='tenant_foundation.Customer'),
        ),
        migrations.AlterField(
            model_name='customercomment',
            name='comment',
            field=models.ForeignKey(help_text='The comment this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='customer_comments', to='tenant_foundation.Comment'),
        ),
        migrations.AlterField(
            model_name='ongoingworkorder',
            name='comments',
            field=models.ManyToManyField(blank=True, help_text='The comments belonging to this ongoing order.', related_name='ongoing_work_orders', through='tenant_foundation.OngoingWorkOrderComment', to='tenant_foundation.Comment'),
        ),
        migrations.AlterField(
            model_name='ongoingworkorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this ongoing order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ongoing_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ongoingworkorder',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom last modified this ongoing order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_ongoing_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ongoingworkordercomment',
            name='about',
            field=models.ForeignKey(help_text='The order whom this comment is about.', on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_work_order_comments', to='tenant_foundation.OngoingWorkOrder'),
        ),
        migrations.AlterField(
            model_name='ongoingworkordercomment',
            name='comment',
            field=models.ForeignKey(help_text='The comment this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_work_order_comments', to='tenant_foundation.Comment'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='tenant_foundation.PublicImageUpload'),
        ),
        migrations.AlterField(
            model_name='organizationassociateaffiliation',
            name='associate',
            field=models.ForeignKey(help_text='The associate of our reference.', on_delete=django.db.models.deletion.CASCADE, related_name='organization_associations', to='tenant_foundation.Associate'),
        ),
        migrations.AlterField(
            model_name='organizationassociateaffiliation',
            name='organization',
            field=models.ForeignKey(help_text='The organization whom this user is affiliated to.', on_delete=django.db.models.deletion.CASCADE, related_name='organization_associations', to='tenant_foundation.Organization'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this partner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='tenant_foundation.PublicImageUpload'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partner',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partner',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that this partner that is affiliated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='tenant_foundation.Organization'),
        ),
        migrations.AlterField(
            model_name='partnercomment',
            name='about',
            field=models.ForeignKey(help_text='The partner whom this comment is about.', on_delete=django.db.models.deletion.CASCADE, related_name='partner_comments', to='tenant_foundation.Partner'),
        ),
        migrations.AlterField(
            model_name='partnercomment',
            name='comment',
            field=models.ForeignKey(help_text='The comment this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='partner_comments', to='tenant_foundation.Comment'),
        ),
        migrations.AlterField(
            model_name='publicimageupload',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_public_image_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicimageupload',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom last modified this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_public_image_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staves', to='tenant_foundation.PublicImageUpload'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_staves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffcomment',
            name='about',
            field=models.ForeignKey(help_text='The staff whom this comment is about.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_comments', to='tenant_foundation.Staff'),
        ),
        migrations.AlterField(
            model_name='staffcomment',
            name='comment',
            field=models.ForeignKey(help_text='The comment this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_comments', to='tenant_foundation.Comment'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='job',
            field=models.ForeignKey(blank=True, help_text='The job order that this task is referencing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to='tenant_foundation.WorkOrder'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom last modified this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_task_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='ongoing_job',
            field=models.ForeignKey(blank=True, help_text='The (ongoing) job order that this task is referencing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to='tenant_foundation.OngoingWorkOrder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='associate',
            field=models.ForeignKey(blank=True, help_text='The associate of our order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='tenant_foundation.Associate'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(help_text='The customer of our order.', on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='tenant_foundation.Customer'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='invoice_service_fee',
            field=models.ForeignKey(blank=True, help_text='The service fee applied by the franchise on the total cost of this job order which will be paid by the associate member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='tenant_foundation.WorkOrderServiceFee'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom last modified this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='latest_pending_task',
            field=models.ForeignKey(blank=True, help_text='The latest pending task of our job order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='tenant_foundation.TaskItem'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='ongoing_work_order',
            field=models.ForeignKey(blank=True, help_text='The ongoing work order that this work order is a part of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='tenant_foundation.OngoingWorkOrder'),
        ),
        migrations.AlterField(
            model_name='workordercomment',
            name='about',
            field=models.ForeignKey(help_text='The order whom this comment is about.', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_comments', to='tenant_foundation.WorkOrder'),
        ),
        migrations.AlterField(
            model_name='workordercomment',
            name='comment',
            field=models.ForeignKey(help_text='The comment this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_comments', to='tenant_foundation.Comment'),
        ),
        migrations.AlterField(
            model_name='workorderservicefee',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_order_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorderservicefee',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom last modified this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_work_order_fees', to=settings.AUTH_USER_MODEL),
        ),
    ]
