# Generated by Django 2.0.10 on 2019-01-30 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0029_auto_20190130_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='visits',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='The the number of visits that were made between the customer and associate for this particular work order.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Visits'),
        ),
    ]
