# Generated by Django 2.0.9 on 2019-01-29 21:31

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0029_auto_20190125_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deactivation_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Blacklisted'), (3, 'Moved'), (4, 'Deceased'), (5, 'Do not contact'), (1, 'Other')], default=1, help_text='The reason why this customer was deactivated.', verbose_name='Deactivation reason'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deactivation_reason_other',
            field=models.CharField(blank=True, default='', help_text='The reason why this customer was deactivated which was not in the list.', max_length=2055, verbose_name='Deactivation reason (other)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=django_fsm.FSMField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='The state of this customer.', max_length=50, verbose_name='State'),
        ),
    ]
