# Generated by Django 2.0.10 on 2019-03-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0030_workorder_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='invoice_ids',
            field=models.CharField(blank=True, default='', help_text='A list of invoice ID values associated with this order.', max_length=1024, null=True, verbose_name='Invoice ID(s)'),
        ),
    ]
