# Generated by Django 2.0.10 on 2019-03-31 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tenant_foundation.models.bulletin_board_item


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_foundation', '0032_auto_20190306_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinBoardItem',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.bulletin_board_item.increment_bulletin_board_item_id_number, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
                ('text', models.TextField(help_text='The text content of this bulletin board item.', verbose_name='Text')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Indicates whether bulletin board item was archived.', verbose_name='Is Archived')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bulletin_board_itemss', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom last modified this away log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_bulletin_board_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin Board Item',
                'verbose_name_plural': 'Bulletin Board Items',
                'db_table': 'workery_bulletin_board_items',
                'ordering': ['-created_at'],
                'permissions': (('can_get_comments', 'Can get comments'), ('can_get_comment', 'Can get comment'), ('can_post_comment', 'Can create comment'), ('can_put_comment', 'Can update comment'), ('can_delete_comment', 'Can delete comment')),
                'default_permissions': (),
            },
        ),
    ]
