# Generated by Django 2.0.10 on 2019-03-31 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0033_bulletinboarditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletinboarditem',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': (('can_get_bulletin_board_items', 'Can get bulletin board items'), ('can_get_bulletin_board_item', 'Can get bulletin board item'), ('can_post_bulletin_board_item', 'Can create bulletin board item'), ('can_put_bulletin_board_item', 'Can update bulletin board item'), ('can_delete_bulletin_board_item', 'Can delete bulletin board item')), 'verbose_name': 'Bulletin Board Item', 'verbose_name_plural': 'Bulletin Board Items'},
        ),
    ]
