# Generated by Django 2.0.10 on 2019-03-31 22:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0034_auto_20190331_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='emergency_contact_alternative_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="The alternative telephone of this associate's primary contact.", max_length=128, null=True, verbose_name='Emergency contact alternative telephone'),
        ),
        migrations.AddField(
            model_name='associate',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text="The name of this associate's primary contact.", max_length=127, null=True, verbose_name='Emergency contact full-name'),
        ),
        migrations.AddField(
            model_name='associate',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text="The relationship of this associate's primary contact.", max_length=127, null=True, verbose_name='Emergency contact relationship'),
        ),
        migrations.AddField(
            model_name='associate',
            name='emergency_contact_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="The telephone of this associate's primary contact.", max_length=128, null=True, verbose_name='Emergency contact telephone'),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_alternative_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="The alternative telephone of this staff member's primary contact.", max_length=128, null=True, verbose_name='Emergency contact alternative telephone'),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text="The name of this staff member's primary contact.", max_length=127, null=True, verbose_name='Emergency contact full-name'),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text="The relationship of this staff member's primary contact.", max_length=127, null=True, verbose_name='Emergency contact relationship'),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="The telephone of this staff member's primary contact.", max_length=128, null=True, verbose_name='Emergency contact telephone'),
        ),
    ]
