# Generated by Django 2.0.10 on 2019-05-04 19:15

from django.db import migrations, models
import django.db.models.deletion
import tenant_foundation.models.how_hear_about_us_item


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0035_auto_20190331_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowHearAboutUsItem',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.how_hear_about_us_item.increment_tag_id_number, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_index=True, help_text='The text content of this item.', max_length=31, unique=True, verbose_name='Text')),
                ('is_for_associate', models.BooleanField(default=True, help_text='Indicates this option will be visible for the associate.', verbose_name='Is for associate')),
                ('is_for_customer', models.BooleanField(default=True, help_text='Indicates this option will be visible for the customer.', verbose_name='Is for customer')),
                ('is_for_staff', models.BooleanField(default=True, help_text='Indicates this option will be visible for the staff.', verbose_name='Is for staff')),
                ('is_for_partner', models.BooleanField(default=True, help_text='Indicates this option will be visible for the partner.', verbose_name='Is for partner')),
            ],
            options={
                'verbose_name': 'How Hear About Us Item',
                'verbose_name_plural': 'How Hear About Us Items',
                'db_table': 'workery_how_hear_about_us_items',
                'permissions': (('can_get_tags', 'Can get tags'), ('can_get_tag', 'Can get tag'), ('can_post_tag', 'Can create tag'), ('can_put_tag', 'Can update tag'), ('can_delete_tag', 'Can delete tag')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='associate',
            name='how_hear_about_us',
            field=models.ForeignKey(blank=True, help_text='How associate heared about this us from a select range of choices.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associates', to='tenant_foundation.HowHearAboutUsItem'),
        ),
        migrations.AddField(
            model_name='customer',
            name='how_hear_about_us',
            field=models.ForeignKey(blank=True, help_text='How customer heared/learned about this Over 55 Inc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='tenant_foundation.HowHearAboutUsItem'),
        ),
        migrations.AddField(
            model_name='partner',
            name='how_hear_about_us',
            field=models.ForeignKey(blank=True, help_text='How partner heared about this business.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='tenant_foundation.HowHearAboutUsItem'),
        ),
        migrations.AddField(
            model_name='staff',
            name='how_hear_about_us',
            field=models.ForeignKey(blank=True, help_text='How this staff member heared about this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staves', to='tenant_foundation.HowHearAboutUsItem'),
        ),
    ]
