# Generated by Django 2.0.10 on 2019-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0036_auto_20190504_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='howhearaboutusitem',
            name='sort_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='The number this item will appear when sorted by number.', verbose_name='Sort #'),
        ),
    ]
