# Generated by Django 2.0.10 on 2019-05-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0037_howhearaboutusitem_sort_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howhearaboutusitem',
            name='text',
            field=models.CharField(db_index=True, help_text='The text content of this item.', max_length=127, unique=True, verbose_name='Text'),
        ),
    ]
