# Generated by Django 2.0.10 on 2019-05-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0038_auto_20190504_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='how_hear',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='how_hear',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='how_hear',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='how_hear',
        ),
        migrations.AddField(
            model_name='associate',
            name='how_hear_old',
            field=models.PositiveSmallIntegerField(blank=True, default=8, help_text='How associate heared about this us from a select range of choices.', verbose_name='Learned about us (old)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='how_hear_old',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='How customer heared/learned about this Over 55 Inc.', verbose_name='Learned about us (old)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='how_hear_old',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How partner heared about this business.', null=True, verbose_name='Learned about us (old)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='how_hear_old',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How this staff member heared about this organization.', null=True, verbose_name='Learned about us (old)'),
        ),
    ]
