# Generated by Django 2.0.13 on 2019-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0040_auto_20190504_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='how_hear_other',
            field=models.CharField(blank=True, help_text='How associate heared about this us in detail.', max_length=2055, null=True, verbose_name='How hear (other)'),
        ),
    ]
