# Generated by Django 2.0.13 on 2019-08-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0041_staff_how_hear_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization_name',
            field=models.CharField(blank=True, help_text='The name of the organization or business this person represents.', max_length=255, null=True, verbose_name='Organization Name'),
        ),
    ]
