# Generated by Django 2.0.13 on 2019-08-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0043_customer_organization_type_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='organization_name',
            field=models.CharField(blank=True, help_text='The name of the organization or business this person represents.', max_length=255, null=True, verbose_name='Organization Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='organization_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unknown Organization Type'), (2, 'Private Organization Type'), (3, 'Non-Profit Organization Type'), (4, 'Government Organization')], default=1, help_text='The type of organization this is based on Over55 internal classification.', verbose_name='Organization Type of'),
        ),
    ]
