# Generated by Django 2.0.13 on 2019-08-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0044_auto_20190818_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='organization_name',
            field=models.CharField(blank=True, help_text='The name of the organization or business this person represents.', max_length=255, null=True, verbose_name='Organization Name'),
        ),
        migrations.AddField(
            model_name='associate',
            name='organization_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unknown Organization Type'), (2, 'Private Organization Type'), (3, 'Non-Profit Organization Type'), (4, 'Government Organization')], default=1, help_text='The type of organization this is based on Over55 internal classification.', verbose_name='Organization Type of'),
        ),
        migrations.AddField(
            model_name='associate',
            name='type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Residential Associate'), (3, 'Commercial Associate'), (1, 'Unknown Associate')], db_index=True, default=1, help_text='The type of customer this is.', verbose_name='Type of'),
        ),
    ]
