# Generated by Django 2.0.13 on 2019-08-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0045_auto_20190825_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Assign associate'), (2, '48 Follow up did customer and associate agree to meet.'), (3, 'Follow up customer survey (Deprecated)'), (4, 'Follow up did associate accept job'), (5, 'Follow up was ongoing job updated'), (6, 'Follow up did associate complete job'), (7, 'Follow up did customer review associate after job')], help_text='The type of task item this is.', verbose_name='Type of'),
        ),
    ]
