# Generated by Django 2.0.13 on 2019-08-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0046_auto_20190828_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='no_survey_conducted_reason',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The reason no survey was conducted.', null=True, verbose_name='No Survey Conducted Reason'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='no_survey_conducted_reason_other',
            field=models.CharField(blank=True, help_text='The specific reason this job order had no survey conducted.', max_length=1024, null=True, verbose_name='No Survey Conducted Reason (Other)'),
        ),
    ]
