# Generated by Django 2.0.13 on 2019-09-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0047_auto_20190830_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='howhearaboutusitem',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether how hear item was archived.', verbose_name='Is Archived'),
        ),
        migrations.AddField(
            model_name='insurancerequirement',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether bulletin board item was archived.', verbose_name='Is Archived'),
        ),
        migrations.AddField(
            model_name='skillset',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether skill set was archived.', verbose_name='Is Archived'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether tag was archived.', verbose_name='Is Archived'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether vehicle type was archived.', verbose_name='Is Archived'),
        ),
        migrations.AddField(
            model_name='workorderservicefee',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether service fee was archived.', verbose_name='Is Archived'),
        ),
    ]
