# Generated by Django 2.0.13 on 2019-09-22 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import tenant_foundation.models.private_file_upload
import tenant_foundation.models.private_image_upload
import workery.s3utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_foundation', '0049_staff_police_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateFileUpload',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.private_file_upload.increment_private_file_upload_id_number, editable=False, primary_key=True, serialize=False)),
                ('data_file', models.FileField(help_text='The upload binary file.', storage=workery.s3utils.PrivateMediaStorage(), upload_to='uploads/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, help_text='The tile content of this upload.', max_length=63, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='The text content of this upload.', null=True, verbose_name='Description')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Indicates whether private file was archived.', verbose_name='Is Archived')),
                ('indexed_text', models.CharField(blank=True, db_index=True, help_text='The searchable content text used by the keyword searcher function.', max_length=511, null=True, unique=True, verbose_name='Indexed Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
            ],
            options={
                'verbose_name': 'Private File Upload',
                'verbose_name_plural': 'Private File Uploads',
                'db_table': 'workery_private_file_uploads',
                'permissions': (('can_get_private_file_uploads', 'Can get private file uploads'), ('can_get_private_file_upload', 'Can get private file upload'), ('can_post_private_file_upload', 'Can create private file upload'), ('can_put_private_file_upload', 'Can update private file upload'), ('can_delete_private_file_upload', 'Can delete private file upload')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PrivateImageUpload',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.private_image_upload.increment_private_image_upload_id_number, editable=False, primary_key=True, serialize=False)),
                ('image_file', sorl.thumbnail.fields.ImageField(help_text='The upload image.', storage=workery.s3utils.PrivateMediaStorage(), upload_to='uploads/%Y/%m/%d/')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Indicates whether private image was archived.', verbose_name='Is Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_private_image_uploads', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom last modified this private image upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_private_image_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Image Upload',
                'verbose_name_plural': 'Private Image Uploads',
                'db_table': 'workery_private_image_uploads',
                'permissions': (('can_get_private_image_uploads', 'Can get private image uploads'), ('can_get_private_image_upload', 'Can get private image upload'), ('can_post_private_image_upload', 'Can create private image upload'), ('can_put_private_image_upload', 'Can update private image upload'), ('can_delete_private_image_upload', 'Can delete private image upload')),
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='associate',
            name='avatar_image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='avatar_image',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='avatar_image',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='avatar_image',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='avatar_image',
        ),
        migrations.AddField(
            model_name='privatefileupload',
            name='associate',
            field=models.ForeignKey(blank=True, help_text='The associate whom this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_file_uploads', to='tenant_foundation.Associate'),
        ),
        migrations.AddField(
            model_name='privatefileupload',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_private_file_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatefileupload',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer whom this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_file_uploads', to='tenant_foundation.Customer'),
        ),
        migrations.AddField(
            model_name='privatefileupload',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom last modified this private file upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_private_file_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatefileupload',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='The partner whom this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_file_uploads', to='tenant_foundation.Partner'),
        ),
        migrations.AddField(
            model_name='privatefileupload',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='The staff whom this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_file_uploads', to='tenant_foundation.Staff'),
        ),
        migrations.AddField(
            model_name='privatefileupload',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this private file uploads.', related_name='private_file_uploads', to='tenant_foundation.Tag'),
        ),
        migrations.AddField(
            model_name='privatefileupload',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='The worker order that this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_file_uploads', to='tenant_foundation.WorkOrder'),
        ),
    ]
