# Generated by Django 2.0.13 on 2019-09-19 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tenant_foundation.models.customer_file_upload
import workery.s3utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_foundation', '0049_staff_police_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFileUpload',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.customer_file_upload.increment_customer_file_upload_id_number, editable=False, primary_key=True, serialize=False)),
                ('binary_file', models.FileField(help_text='The upload binary file.', storage=workery.s3utils.PrivateMediaStorage(), upload_to='uploads/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filess', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='The customer whom this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='tenant_foundation.Customer')),
            ],
            options={
                'verbose_name': 'Customer File Upload',
                'verbose_name_plural': 'Customer File Uploads',
                'db_table': 'workery_customer_file_uploads',
                'permissions': (('can_get_customer_file_uploads', 'Can get customer file uploads'), ('can_get_customer_file_upload', 'Can get customer file upload'), ('can_post_customer_file_upload', 'Can create customer file upload'), ('can_put_customer_file_upload', 'Can update customer file upload'), ('can_delete_customer_file_upload', 'Can delete customer file upload')),
                'default_permissions': (),
            },
        ),
    ]
