# Generated by Django 2.0.13 on 2019-09-21 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tenant_foundation.models.private_file_upload
import workery.s3utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_foundation', '0049_staff_police_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateFileUpload',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.private_file_upload.increment_private_file_upload_id_number, editable=False, primary_key=True, serialize=False)),
                ('binary_file', models.FileField(help_text='The upload binary file.', storage=workery.s3utils.PrivateMediaStorage(), upload_to='uploads/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, help_text='The tile content of this upload.', max_length=63, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='The text content of this upload.', null=True, verbose_name='Description')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Indicates whether private file was archived.', verbose_name='Is Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the creator.', null=True, verbose_name='Created from')),
                ('created_from_is_public', models.BooleanField(default=False, help_text='Is creator a public IP and is routable.', verbose_name='Is the IP ')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_from', models.GenericIPAddressField(blank=True, help_text='The IP address of the modifier.', null=True, verbose_name='Last modified from')),
                ('last_modified_from_is_public', models.BooleanField(default=False, help_text='Is modifier a public IP and is routable.', verbose_name='Is the IP ')),
                ('associate', models.ForeignKey(blank=True, help_text='The associate whom this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_file_uploads', to='tenant_foundation.Associate')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user whom created this file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_private_file_uploads', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='The customer whom this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_file_uploads', to='tenant_foundation.Customer')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='The user whom last modified this private file upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_private_file_uploads', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, help_text='The partner whom this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_file_uploads', to='tenant_foundation.Partner')),
                ('staff', models.ForeignKey(blank=True, help_text='The staff whom this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_file_uploads', to='tenant_foundation.Staff')),
                ('tags', models.ManyToManyField(blank=True, help_text='The tags associated with this private file uploads.', related_name='private_file_uploads', to='tenant_foundation.Tag')),
                ('work_order', models.ForeignKey(blank=True, help_text='The worker order that this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_file_uploads', to='tenant_foundation.WorkOrder')),
            ],
            options={
                'verbose_name': 'Private File Upload',
                'verbose_name_plural': 'Private File Uploads',
                'db_table': 'workery_private_file_uploads',
                'permissions': (('can_get_private_file_uploads', 'Can get private file uploads'), ('can_get_private_file_upload', 'Can get private file upload'), ('can_post_private_file_upload', 'Can create private file upload'), ('can_put_private_file_upload', 'Can update private file upload'), ('can_delete_private_file_upload', 'Can delete private file upload')),
                'default_permissions': (),
            },
        ),
    ]
