# Generated by Django 2.0.13 on 2019-09-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0050_auto_20190922_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this associate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associates', to='tenant_foundation.PrivateImageUpload'),
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='tenant_foundation.PrivateImageUpload'),
        ),
        migrations.AddField(
            model_name='organization',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='tenant_foundation.PrivateImageUpload'),
        ),
        migrations.AddField(
            model_name='partner',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this partner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='tenant_foundation.PrivateImageUpload'),
        ),
        migrations.AddField(
            model_name='staff',
            name='avatar_image',
            field=models.ForeignKey(blank=True, help_text='The avatar image of this staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staves', to='tenant_foundation.PrivateImageUpload'),
        ),
    ]
