# Generated by Django 2.0.13 on 2019-09-19 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0050_customerfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfileupload',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_file_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerfileupload',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer whom this file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to='tenant_foundation.Customer'),
        ),
    ]
