# Generated by Django 2.0.13 on 2019-09-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0051_auto_20190922_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatefileupload',
            name='indexed_text',
            field=models.CharField(blank=True, db_index=True, help_text='The searchable content text used by the keyword searcher function.', max_length=511, null=True, unique=True, verbose_name='Indexed Text'),
        ),
    ]
