# Generated by Django 2.0.13 on 2019-09-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0051_auto_20190922_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='cloned_from',
            field=models.ForeignKey(blank=True, help_text='The original work order this order was cloned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_work_orders', to='tenant_foundation.WorkOrder'),
        ),
    ]
