# Generated by Django 2.0.13 on 2019-10-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0054_auto_20190930_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderinvoice',
            name='client_address',
            field=models.CharField(blank=True, help_text='The address of the client on this invoice document.', max_length=63, null=True, verbose_name='Client Address'),
        ),
    ]
