# Generated by Django 2.0.13 on 2019-10-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0055_workorderinvoice_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderinvoice',
            name='revision_version',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The revision identifier to keep track what version this invoice is with our edit. Every edit submission results in this value being incremented by 1.', null=True, verbose_name='Revision Version'),
        ),
    ]
