# Generated by Django 2.0.13 on 2019-10-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0060_workorder_invoice_paid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderinvoice',
            name='invoice_id',
            field=models.CharField(blank=True, help_text='Indicates what invoice ID is referenced on the document.', max_length=127, null=True, verbose_name='Invoice ID'),
        ),
    ]
