# Generated by Django 2.0.13 on 2019-10-11 04:26

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0065_auto_20191011_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorderinvoice',
            old_name='sub_total_currency',
            new_name='amount_due_currency',
        ),
        migrations.RemoveField(
            model_name='workorderinvoice',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='workorderinvoice',
            name='amount_due',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='CAD', help_text='Amount Due', max_digits=10, verbose_name='Amount Due'),
        ),
    ]
