# Generated by Django 2.0.13 on 2019-10-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0069_auto_20191019_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='service_fee',
            field=models.ForeignKey(blank=True, help_text='The service fee assigned for this associate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associates', to='tenant_foundation.WorkOrderServiceFee'),
        ),
    ]
