# Generated by Django 2.0.13 on 2019-11-09 18:57

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0070_associate_service_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='invoice_quoted_waste_removal_amount_currency',
            new_name='invoice_other_costs_amount_currency',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='invoice_waste_removal_amount_currency',
            new_name='invoice_quoted_other_costs_amount_currency',
        ),
        migrations.RenameField(
            model_name='workorderinvoice',
            old_name='waste_removal',
            new_name='other_costs',
        ),
        migrations.RenameField(
            model_name='workorderinvoice',
            old_name='waste_removal_currency',
            new_name='other_costs_currency',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='invoice_quoted_waste_removal_amount',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='invoice_waste_removal_amount',
        ),
        migrations.AddField(
            model_name='workorder',
            name='invoice_other_costs_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='CAD', help_text='The amount charged for other costs by the associate for this job.', max_digits=10, verbose_name='Other Costs Amount'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='invoice_quoted_other_costs_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='CAD', help_text='The quoted other costs amount to charge by the associate for this job.', max_digits=10, verbose_name='Other Costs Amount'),
        ),
    ]
