# Generated by Django 2.0.13 on 2020-03-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0072_unifiedsearchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='closing_reason_comment',
            field=models.CharField(blank=True, default='', help_text='Details as to why the job was closed.', max_length=1024, null=True, verbose_name='Closing Reason comment'),
        ),
    ]
