# Generated by Django 2.0.13 on 2020-03-11 04:00

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0075_auto_20200310_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingworkorder',
            name='state',
            field=django_fsm.FSMField(blank=True, db_index=True, default='running', help_text='The state of this ongoing work order.', max_length=50, verbose_name='State'),
        ),
    ]
