# Generated by Django 2.0 on 2017-12-24 00:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import shared_foundation.models.me
import shared_foundation.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(help_text='The official name of this Franchise.', max_length=127, verbose_name='Name')),
                ('alternate_name', models.CharField(blank=True, help_text='An alias for this Franchise.', max_length=127, null=True, verbose_name='Alternate Name')),
                ('description', models.TextField(blank=True, help_text='The detailed description about this Franchise.', verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Franchise',
                'verbose_name_plural': 'Franchises',
                'db_table': 'o55_franchises',
            },
        ),
        migrations.CreateModel(
            name='SharedFranchiseDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='shared_foundation.SharedFranchise')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'o55_franchise_domains',
            },
        ),
        migrations.CreateModel(
            name='SharedMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('salt', models.CharField(blank=True, default=shared_foundation.utils.generate_hash, help_text='The unique salt value associated with this object.', max_length=127, null=True, unique=True, verbose_name='Salt')),
                ('pr_access_code', models.CharField(blank=True, default=shared_foundation.utils.generate_hash, help_text='The access code to enter the password reset page to be granted access to restart your password.', max_length=127, verbose_name='Password Reset Access Code')),
                ('pr_expiry_date', models.DateTimeField(blank=True, default=shared_foundation.models.me.get_expiry_date, help_text='The date where the access code expires and no longer works.', verbose_name='Password Reset Access Code Expiry Date')),
            ],
            options={
                'verbose_name': 'Me',
                'verbose_name_plural': 'Mes',
                'db_table': 'o55_mes',
            },
        ),
        migrations.CreateModel(
            name='O55User',
            fields=[
            ],
            options={
                'verbose_name': 'O55 User',
                'verbose_name_plural': 'O55 Users',
                'ordering': ('-email',),
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='sharedme',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The user whom is associated with this profile.', null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_foundation.O55User'),
        ),
        migrations.AddField(
            model_name='sharedfranchise',
            name='frontline_staff',
            field=models.ManyToManyField(blank=True, help_text='The office staff and or volunteers who belong to this "Franchise".', related_name='shared_foundation_sharedfranchise_frontline_staff_related', to='shared_foundation.O55User'),
        ),
        migrations.AddField(
            model_name='sharedfranchise',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='The managers who belong to this "Franchise" and are administrators or have executive decision making authority.', related_name='shared_foundation_sharedfranchise_managers_related', to='shared_foundation.O55User'),
        ),
    ]
