# Generated by Django 2.0.3 on 2018-03-26 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareduser',
            name='franchise',
            field=models.ForeignKey(blank=True, help_text='The franchise whom this profile belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared_foundation.SharedFranchise'),
        ),
    ]
