# Generated by Django 2.0 on 2017-12-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedopeninghoursspecification',
            name='closes',
            field=models.CharField(blank=True, help_text='The closing hour of the place or service on the given day(s) of the week.', max_length=15, null=True, verbose_name='Closes'),
        ),
        migrations.AlterField(
            model_name='sharedopeninghoursspecification',
            name='opens',
            field=models.CharField(blank=True, help_text='The opening hour of the place or service on the given day(s) of the week.', max_length=15, null=True, verbose_name='Opens'),
        ),
    ]
