# Generated by Django 2.0 on 2017-12-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfranchise',
            name='customers',
            field=models.ManyToManyField(blank=True, help_text='The customers who belong to this "Franchise".', related_name='shared_foundation_sharedfranchise_customers_related', to='shared_foundation.O55User'),
        ),
    ]
