# Generated by Django 2.0.2 on 2018-03-05 01:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfranchise',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='The fax number.', max_length=128, null=True, verbose_name='Fax Number'),
        ),
        migrations.AlterField(
            model_name='sharedfranchise',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, help_text='The mobile telephone number.', max_length=128, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='sharedfranchise',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='The telephone number.', max_length=128, null=True, verbose_name='Telephone'),
        ),
    ]
