# Generated by Django 2.0 on 2017-12-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedme',
            name='cell_num',
            field=models.CharField(blank=True, help_text="The cell number of this person's profile.", max_length=16, null=True, verbose_name='Cell Number'),
        ),
        migrations.AddField(
            model_name='sharedme',
            name='tel_ext_num',
            field=models.CharField(blank=True, help_text="The telephone extension number of this person's profile.", max_length=7, null=True, verbose_name='Telephone Extension Number'),
        ),
        migrations.AddField(
            model_name='sharedme',
            name='tel_num',
            field=models.CharField(blank=True, help_text="The telephone number of this person's profile.", max_length=16, null=True, verbose_name='Telephone Number'),
        ),
        migrations.AlterField(
            model_name='sharedme',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The user whom is owns this profile.', null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_foundation.O55User'),
        ),
    ]
