# Generated by Django 2.0 on 2018-01-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedme',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='address_locality',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='address_region',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='area_served',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='available_language',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='fax_number',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='hours_available',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='post_office_box_number',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='product_supported',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='street_address_extra',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='sharedme',
            name='telephone_extension',
        ),
        migrations.AlterField(
            model_name='sharedme',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
