# Generated by Django 2.0 on 2017-12-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0002_auto_20171227_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedopeninghoursspecification',
            name='day_of_week',
            field=models.CharField(blank=True, help_text='The day of the week for which these opening hours are valid.', max_length=15, null=True, verbose_name='Day Of Week'),
        ),
    ]
