# Generated by Django 2.0 on 2018-01-26 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0002_auto_20180126_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfranchise',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='sharedfranchise',
            name='frontline_staff',
        ),
        migrations.RemoveField(
            model_name='sharedfranchise',
            name='managers',
        ),
        migrations.AddField(
            model_name='sharedme',
            name='franchise',
            field=models.OneToOneField(blank=True, help_text='The franchise whom this profile belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_foundation.SharedFranchise'),
        ),
    ]
