# Generated by Django 2.0 on 2018-01-26 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0003_auto_20180126_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedme',
            name='franchise',
            field=models.ForeignKey(blank=True, help_text='The franchise whom this profile belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_foundation.SharedFranchise'),
        ),
    ]
