# Generated by Django 2.0.7 on 2018-07-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfranchise',
            name='currency',
            field=models.CharField(blank=True, default='CAD', help_text='The currency used by this franchise formatted in <a href="https://en.wikipedia.org/wiki/ISO_4217">ISO 4217</a> formatting.', max_length=3, verbose_name='Currency'),
        ),
    ]
