# Generated by Django 2.0.5 on 2018-05-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfranchise',
            name='other_telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone the alternative telephone is. Ex: work, home, etc.', verbose_name='Other telephone type of'),
        ),
        migrations.AlterField(
            model_name='sharedfranchise',
            name='telephone_type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Telephone'), (2, 'Mobile'), (3, 'Work Telephone')], default=1, help_text='The type of phone this is. Ex: work, home, etc.', verbose_name='Telephone type of'),
        ),
    ]
