# Generated by Django 2.0.4 on 2018-05-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0002_sharedfranchise_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfranchise',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether this franchise was archived.', verbose_name='Is Archived'),
        ),
    ]
