# -*- coding: utf-8 -*-
from tenant_api.views.associate import AssociateListCreateAPIView, AssociateRetrieveUpdateDestroyAPIView, AssociateCreateValidationAPIView
from tenant_api.views.associate_comment import AssociateCommentListCreateAPIView
from tenant_api.views.awaylog import AwayLogListCreateAPIView, AwayLogRetrieveUpdateDestroyAPIView
# from tenant_api.views.comment import CommentListCreateAPIView, CommentRetrieveUpdateDestroyAPIView
from tenant_api.views.customer import CustomerListCreateAPIView, CustomerRetrieveUpdateDestroyAPIView, CustomerCreateValidationAPIView
from tenant_api.views.customer_comment import CustomerCommentListCreateAPIView
from tenant_api.views.insurance_requirement import InsuranceRequirementListCreateAPIView, InsuranceRequirementRetrieveUpdateDestroyAPIView
from tenant_api.views.order import OrderListCreateAPIView, OrderRetrieveUpdateDestroyAPIView
from tenant_api.views.order_comment import OrderCommentListCreateAPIView
from tenant_api.views.partner import PartnerListCreateAPIView, PartnerRetrieveUpdateDestroyAPIView, PartnerCreateValidationAPIView
from tenant_api.views.partner_comment import PartnerCommentListCreateAPIView
from tenant_api.views.skill_set import SkillSetListCreateAPIView, SkillSetRetrieveUpdateDestroyAPIView
from tenant_api.views.staff import StaffListCreateAPIView, StaffRetrieveUpdateDestroyAPIView, StaffCreateValidationAPIView
from tenant_api.views.staff_comment import StaffCommentListCreateAPIView
from tenant_api.views.tag import TagListCreateAPIView, TagRetrieveUpdateDestroyAPIView
from tenant_api.views.utility import FindCustomerMatchingAPIView
from tenant_api.views.order_activite_sheet_item import ActivitySheetItemCreateAPIView
from tenant_api.views.order_complete import OrderCompleteCreateAPIView
from tenant_api.views.order_close import OrderCloseCreateAPIView
from tenant_api.views.order_postpone import OrderPostponeCreateAPIView
from tenant_api.views.order_unassign import OrderUnassignCreateAPIView
from tenant_api.views.order_service_fee import OrderServiceFeeListCreateAPIView, OrderServiceFeeRetrieveUpdateDestroyAPIView
