# -*- coding: utf-8 -*-
from tenant_api.views.associate_operations.associate_avatar_create_or_update import AssociateAvatarCreateOrUpdateOperationCreateAPIView
from tenant_api.views.associate_operations.associate_balance_operation import AssociateBalanceOperationAPIView
from tenant_api.views.associate_operations.associate_password_operation import AssociateChangePasswordOperationAPIView
from tenant_api.views.associate_operations.associate_upgrade_operation import AssociateUprageOperationAPIView
