# -*- coding: utf-8 -*-
from tenant_api.serializers.associate_crud.associate_contact_update import AssociateContactUpdateSerializer
from tenant_api.serializers.associate_crud.associate_address_update import AssociateAddressUpdateSerializer
from tenant_api.serializers.associate_crud.associate_account_update import AssociateAccountUpdateSerializer
from tenant_api.serializers.associate_crud.associate_metrics_update import AssociateMetricsUpdateSerializer
