# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _


AFFILIATION_TYPE_AFFILIATION_ID = 1
AFFILIATION_TYPE_ALUMNI_OF_ID = 2
AFFILIATION_TYPE_FUNDER_ID = 3
AFFILIATION_TYPE_MEMBER_OF_ID = 4
AFFILIATION_TYPE_SPONSOR_ID = 5
AFFILIATION_TYPE_OWNS_ID = 6
AFFILIATION_TYPE_FOUNDER_ID = 7


AFFILIATION_TYPE_OF_CHOICES = (
    (AFFILIATION_TYPE_AFFILIATION_ID, _('Affiliation')),
    (AFFILIATION_TYPE_ALUMNI_OF_ID, _('Alumni Of')),
    (AFFILIATION_TYPE_FUNDER_ID, _('Funder')),
    (AFFILIATION_TYPE_MEMBER_OF_ID, _('Member Of')),
    (AFFILIATION_TYPE_SPONSOR_ID, _('Sponsor')),
    (AFFILIATION_TYPE_OWNS_ID, _('Owns')),
    (AFFILIATION_TYPE_FOUNDER_ID, _('Founder')),
)
