# Generated by Django 2.0 on 2017-12-26 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import starterkit.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('given_name', models.CharField(blank=True, help_text='The employees given name.', max_length=63, null=True, verbose_name='Given Name')),
                ('middle_name', models.CharField(blank=True, help_text='The employees last name.', max_length=63, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, help_text='The employees last name.', max_length=63, null=True, verbose_name='Last Name')),
                ('business', models.CharField(blank=True, help_text='The employees business status.', max_length=63, null=True, verbose_name='Business')),
                ('is_active', models.BooleanField(default=False, help_text='Track whether this employee is active.', verbose_name='Is Active')),
                ('birthdate', models.DateTimeField(blank=True, help_text='The employees birthdate.', null=True, verbose_name='Birthdate')),
                ('address', models.CharField(blank=True, help_text='The employees address.', max_length=127, null=True, verbose_name='Address')),
                ('join_date', models.DateTimeField(blank=True, help_text='The date the employee joined.', null=True, verbose_name='Join Date')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='The phone number of the employee.', max_length=16, null=True, verbose_name='Phone Number')),
                ('fax', models.CharField(blank=True, help_text='The fax number of the employee.', max_length=16, null=True, verbose_name='Fax Number')),
                ('cell', models.CharField(blank=True, db_index=True, help_text='The cell number of the employee.', max_length=16, null=True, verbose_name='Cell Number')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='The email of this employee.', max_length=254, null=True, verbose_name='Email')),
                ('city', models.CharField(db_index=True, help_text='The city this employee lives in.', max_length=31, verbose_name='City')),
                ('province', models.CharField(blank=True, db_index=True, help_text='The province this employee lives in.', max_length=15, null=True, verbose_name='Province')),
                ('postal_code', models.CharField(blank=True, db_index=True, help_text='The postal code. For example, 94043.', max_length=11, null=True, verbose_name='Postal Code')),
                ('ldn_area', models.CharField(blank=True, help_text='The area in London that this employee lives in.', max_length=7, null=True, verbose_name='London Area')),
                ('hourly_salary_desired', models.PositiveSmallIntegerField(blank=True, help_text='The hourly salary rate the employee', null=True, verbose_name='Hourly Salary Desired')),
                ('limit_special', models.CharField(blank=True, help_text='Any special limitations / handicaps this employee has.', max_length=63, null=True, verbose_name='Limit Special')),
                ('dues_pd', models.DateTimeField(blank=True, help_text='-', null=True, verbose_name='Deus PD')),
                ('ins_due', models.DateTimeField(blank=True, help_text='-', null=True, verbose_name='Ins Due')),
                ('police_check', models.DateTimeField(blank=True, help_text='The date the employee took a police check.', null=True, verbose_name='Police Check')),
                ('comments', models.CharField(blank=True, help_text='The comments associated with this employee.', max_length=1027, null=True, verbose_name='Comments')),
                ('drivers_license_class', models.CharField(blank=True, help_text='The employees license class for driving.', max_length=3, null=True, verbose_name='Divers License Class')),
                ('has_car', models.BooleanField(default=False, help_text='Indicates whether employee has a car or not.', verbose_name='Has Car')),
                ('has_van', models.BooleanField(default=False, help_text='Indicates whether employee has a van or not.', verbose_name='Has Van')),
                ('has_truck', models.BooleanField(default=False, help_text='Indicates whether employee has a truck or not.', verbose_name='Has Truck')),
                ('is_full_time', models.BooleanField(default=False, help_text='Indicates whether employee is full time or not.', verbose_name='Is Full Time')),
                ('is_part_time', models.BooleanField(default=False, help_text='Indicates whether employee is part time or not.', verbose_name='Is Part Time')),
                ('is_contract_time', models.BooleanField(default=False, help_text='Indicates whether employee is contracted or not.', verbose_name='Is Contract Time')),
                ('is_small_job', models.BooleanField(default=False, help_text='Indicates whether employee is employed for small jobs or not.', verbose_name='Is Small Job')),
                ('how_hear', models.CharField(blank=True, help_text='How employee heared about this business.', max_length=2, null=True, verbose_name='How hear')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('salt', models.CharField(blank=True, default=starterkit.utils.generate_hash, help_text='The unique salt value associated with this object.', max_length=127, null=True, unique=True, verbose_name='Salt')),
                ('user', models.OneToOneField(blank=True, help_text='The user whom belongs to this employee.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staves',
                'db_table': 'o55_staff',
            },
        ),
    ]
