# Generated by Django 2.0.4 on 2018-04-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A description of the skill set.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A short description of this tag.', null=True, verbose_name='Description'),
        ),
    ]
