# Generated by Django 2.0 on 2017-12-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area_served',
            field=models.CharField(blank=True, help_text='The geographic area where a service or offered item is provided.', max_length=127, null=True, verbose_name='Area Served'),
        ),
        migrations.AddField(
            model_name='customer',
            name='available_language',
            field=models.CharField(blank=True, help_text='A language someone may use with or at the item, service or place. Please use one of the language codes from the <a href="https://tools.ietf.org/html/bcp47">IETF BCP 47 standard</a>.', max_length=127, null=True, verbose_name='Available Language'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_type',
            field=models.CharField(blank=True, help_text='A person or organization can have different contact points, for different purposes. For example, a sales contact point, a PR contact point and so on. This property is used to specify the kind of contact point.', max_length=127, null=True, verbose_name='Contact Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fax_number',
            field=models.CharField(blank=True, help_text='The fax number.', max_length=31, null=True, verbose_name='Fax Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='hours_available',
            field=models.ManyToManyField(blank=True, help_text='The hours during which this service or contact is available.', related_name='tenant_foundation_customer_contact_point_hours_available_related', to='tenant_foundation.OpeningHoursSpecification'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, help_text='The mobile telephone number.', max_length=31, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='product_supported',
            field=models.CharField(blank=True, default='', help_text='The product or service this support contact point is related to (such as product support for a particular product line). This can be a specific product or product line (e.g. "iPhone") or a general category of products or services (e.g. "smartphones").', max_length=31, null=True, verbose_name='Product Supported'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, default='', help_text='The telephone number.', max_length=31, null=True, verbose_name='Telephone'),
        ),
    ]
