# Generated by Django 2.0.4 on 2018-05-11 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that this partner that is affiliated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_foundation.Organization'),
        ),
    ]
