# Generated by Django 2.0.4 on 2018-04-12 20:39

from django.db import migrations, models
import tenant_foundation.models.order


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(db_index=True, default=tenant_foundation.models.order.increment_order_id_number, editable=False, primary_key=True, serialize=False),
        ),
    ]
