# Generated by Django 2.0.4 on 2018-04-30 22:05

from django.db import migrations, models
import django.db.models.deletion
import tenant_foundation.models.activity_sheet_item


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySheetItem',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.activity_sheet_item.increment_activity_sheet_item_id_number, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.TextField(blank=True, default='', help_text='A comment associated with this activity sheet.', null=True, verbose_name='Comment')),
                ('has_accepted_job', models.BooleanField(default=True, help_text='Indicates whether associate allows being reached by email', verbose_name='Has Accepted Job')),
                ('associate', models.ForeignKey(help_text='The associate with this activity sheet.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_activitysheetitem_associate_related', to='tenant_foundation.Associate')),
                ('order', models.ForeignKey(help_text='The order associated with thie activity sheet.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_activitysheetitem_orders_related', to='tenant_foundation.Order')),
            ],
            options={
                'verbose_name': 'Activity Sheet Item',
                'verbose_name_plural': 'Activity Sheet Items',
                'db_table': 'o55_activity_sheet_items',
                'ordering': ['-created_at'],
                'permissions': (('can_get_activity_sheet_items', 'Can get activity sheets'), ('can_get_activity_sheet_item', 'Can get activity sheet'), ('can_post_activity_sheet_item', 'Can create activity sheet'), ('can_put_activity_sheet_item', 'Can update activity sheet'), ('can_delete_activity_sheet_item', 'Can delete activity sheet')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='associate',
            name='activity_sheet',
            field=models.ManyToManyField(blank=True, help_text='The activity sheet items of the orders the associate accepted or rejected.', related_name='tenant_foundation_associate_activity_sheet_items_related', through='tenant_foundation.ActivitySheetItem', to='tenant_foundation.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='activity_sheet',
            field=models.ManyToManyField(blank=True, help_text='The activity sheet items related to the associates who accepted or rejected this order.', related_name='tenant_foundation_order_activity_sheet_items_related', through='tenant_foundation.ActivitySheetItem', to='tenant_foundation.Associate'),
        ),
    ]
