# Generated by Django 2.0.2 on 2018-03-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, help_text='Gender of the person. While Male and Female may be used, text strings are also acceptable for people who do not identify as a binary gender.', max_length=63, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality of the person.', max_length=63, null=True, verbose_name='Nationality'),
        ),
    ]
