# Generated by Django 2.0 on 2018-02-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='given_name',
            field=models.CharField(blank=True, db_index=True, help_text='The associates given name.', max_length=63, null=True, verbose_name='Given Name'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, help_text='The associates last name.', max_length=63, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, help_text='The associates last name.', max_length=63, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The name of the item.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='given_name',
            field=models.CharField(blank=True, db_index=True, help_text='The customers given name.', max_length=63, null=True, verbose_name='Given Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, help_text='The customers last name.', max_length=63, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, help_text='The customers last name.', max_length=63, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The name of the item.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='openinghoursspecification',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The name of the item.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The name of the item.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The name of the item.', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
