# Generated by Django 2.0 on 2018-02-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality of the person.', max_length=63, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='how_hear',
            field=models.CharField(blank=True, help_text='How customer heared/learned about this Over 55 Inc.', max_length=2055, null=True, verbose_name='Learned about Over 55'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job_info_read',
            field=models.CharField(blank=True, help_text="The volunteer's name whom received this customer.", max_length=255, null=True, verbose_name='Job information received by'),
        ),
    ]
