# Generated by Django 2.0.4 on 2018-04-25 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awaylog',
            name='user',
        ),
        migrations.AddField(
            model_name='awaylog',
            name='associate',
            field=models.ForeignKey(blank=True, help_text='The associate of our away log.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_awaylog_associate_related', to='tenant_foundation.Associate'),
        ),
    ]
