# Generated by Django 2.0.2 on 2018-03-17 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_staff_created_by_related', to='shared_foundation.O55User'),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_staff_last_modified_by_related', to='shared_foundation.O55User'),
        ),
    ]
