# Generated by Django 2.0.4 on 2018-04-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='skill_sets',
        ),
    ]
