# Generated by Django 2.0.4 on 2018-04-13 04:28

from django.db import migrations, models
import tenant_foundation.models.opening_hours_specification
import tenant_foundation.models.skill_set
import tenant_foundation.models.tag


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghoursspecification',
            name='id',
            field=models.BigAutoField(db_index=True, default=tenant_foundation.models.opening_hours_specification.increment_opening_hours_specification_id_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='id',
            field=models.BigAutoField(db_index=True, default=tenant_foundation.models.skill_set.increment_skillset_id_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(db_index=True, default=tenant_foundation.models.tag.increment_tag_id_number, editable=False, primary_key=True, serialize=False),
        ),
    ]
