# Generated by Django 2.0 on 2017-12-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthdate',
            field=models.DateTimeField(blank=True, help_text='The customers birthdate.', null=True, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='given_name',
            field=models.CharField(blank=True, help_text='The customers given name.', max_length=63, null=True, verbose_name='Given Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, help_text='The customers last name.', max_length=63, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, help_text='The customers last name.', max_length=63, null=True, verbose_name='Middle Name'),
        ),
    ]
