# Generated by Django 2.0.3 on 2018-03-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='parent_organization',
        ),
    ]
