# Generated by Django 2.0.3 on 2018-04-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_ongoing',
            field=models.BooleanField(default=False, help_text='Track whether this order is ongoing job or one-time job.', verbose_name='Is ongoing'),
        ),
    ]
