# Generated by Django 2.0 on 2018-01-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='job_info_read',
            field=models.CharField(blank=True, help_text='-', max_length=255, null=True, verbose_name='Job Info Read'),
        ),
    ]
