# Generated by Django 2.0 on 2017-12-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='salt',
        ),
    ]
