# Generated by Django 2.0.4 on 2018-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='business',
            field=models.CharField(blank=True, help_text='The associates business status.', max_length=63, null=True, verbose_name='Business'),
        ),
    ]
