# Generated by Django 2.0.4 on 2018-05-10 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latest_pending_task',
            field=models.ForeignKey(blank=True, help_text='The latest pending task of our job order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_order_latest_pending_task_related', to='tenant_foundation.TaskItem'),
        ),
    ]
