# Generated by Django 2.0.4 on 2018-04-19 01:45

from django.db import migrations, models
import tenant_foundation.models.resource_category


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.resource_category.increment_resource_category_id_number, editable=False, primary_key=True, serialize=False)),
                ('icon', models.CharField(db_index=True, help_text='The icon of this resource category.', max_length=31, unique=True, verbose_name='icon')),
                ('title', models.CharField(db_index=True, help_text='The title of this resource category.', max_length=63, unique=True, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', help_text='A short description of this resource category.', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'db_table': 'o55_resource_categories',
                'permissions': (('can_get_resource_categories', 'Can get resource_categories'), ('can_get_resource_category', 'Can get resource_category'), ('can_post_resource_category', 'Can create resource_category'), ('can_put_resource_category', 'Can update resource_category'), ('can_delete_resource_category', 'Can delete resource_category')),
                'default_permissions': (),
            },
        ),
    ]
