# Generated by Django 2.0 on 2018-01-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='The organizations that this customer is affiliated with.', through='tenant_foundation.CustomerAffiliation', to='tenant_foundation.Organization'),
        ),
    ]
