# Generated by Django 2.0.4 on 2018-05-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaylog',
            name='associate',
            field=models.OneToOneField(default=1, help_text='The associate of our away log.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_awaylog_associate_related', to='tenant_foundation.Associate'),
            preserve_default=False,
        ),
    ]
