# Generated by Django 2.0.4 on 2018-04-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='dues_pd',
            field=models.DateField(blank=True, help_text='-', null=True, verbose_name='Deus PD'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='ins_due',
            field=models.DateField(blank=True, help_text='-', null=True, verbose_name='Ins Due'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='police_check',
            field=models.DateField(blank=True, help_text='The date the associate took a police check.', null=True, verbose_name='Police Check'),
        ),
    ]
