# Generated by Django 2.0 on 2017-12-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='telephone_extension',
            field=models.CharField(blank=True, default='', help_text='The telephone extension for the number.', max_length=31, null=True, verbose_name='Telephone Extension'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telephone_extension',
            field=models.CharField(blank=True, default='', help_text='The telephone extension for the number.', max_length=31, null=True, verbose_name='Telephone Extension'),
        ),
        migrations.AddField(
            model_name='organization',
            name='telephone_extension',
            field=models.CharField(blank=True, default='', help_text='The telephone extension for the number.', max_length=31, null=True, verbose_name='Telephone Extension'),
        ),
    ]
