# Generated by Django 2.0.4 on 2018-04-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type_of',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Residential Customer'), (3, 'Commercial Customer'), (1, 'Unknown Customer')], db_index=True, default=1, help_text='The type of customer this is.', verbose_name='Type of'),
        ),
    ]
