# Generated by Django 2.0.4 on 2018-04-30 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_foundation', '0002_auto_20180430_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysheetitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this activity sheet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_activitysheetitem_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitysheetitem',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='A comment associated with this activity sheet item.', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='activitysheetitem',
            name='has_accepted_job',
            field=models.BooleanField(default=True, help_text='Indicates whether associate has accepted or rejected this job offer.', verbose_name='Has Accepted Job'),
        ),
    ]
