# Generated by Django 2.0.4 on 2018-05-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20180507_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='away_log',
            field=models.ForeignKey(blank=True, help_text='The object referencing our Assocaites away log (if they have one).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_associate_away_info_related', to='tenant_foundation.AwayLog'),
        ),
    ]
