# Generated by Django 2.0.4 on 2018-05-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_partner_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='awaylog',
            name='was_deleted',
            field=models.BooleanField(default=False, help_text='Track whether this away log was deleted or not.', verbose_name='Was deleted'),
        ),
    ]
