# Generated by Django 2.0 on 2018-02-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20180216_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_business',
            field=models.BooleanField(default=False, help_text='Indicates whether customer is considered a business representive or not.', verbose_name='Is Business'),
        ),
    ]
