# Generated by Django 2.0 on 2018-02-18 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20180218_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email address.', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Invalid email')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The telephone number.', max_length=31, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email address.', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Invalid email')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The telephone number.', max_length=31, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email address.', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Invalid email')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The telephone number.', max_length=31, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email address.', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Invalid email')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The telephone number.', max_length=31, null=True, verbose_name='Telephone'),
        ),
    ]
