# Generated by Django 2.0.4 on 2018-05-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_order_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='follow_up_days_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The number of days from now to follow up on for the ongoing job.', verbose_name='Follow Up Days Number'),
        ),
    ]
