# Generated by Django 2.0.4 on 2018-04-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20180412_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this associate.', related_name='tenant_foundation_associate_tags_related', to='tenant_foundation.Tag'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this customer.', related_name='tenant_foundation_customer_tags_related', to='tenant_foundation.Tag'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this organization.', related_name='tenant_foundation_organization_tags_related', to='tenant_foundation.Tag'),
        ),
        migrations.AddField(
            model_name='staff',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this staff member.', related_name='tenant_foundation_staff_tags_related', to='tenant_foundation.Tag'),
        ),
    ]
