# Generated by Django 2.0 on 2017-12-30 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_foundation', '0002_auto_20171230_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='associate',
            name='alternate_name',
            field=models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name'),
        ),
        migrations.AddField(
            model_name='associate',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A short description of the item.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='associate',
            name='name',
            field=models.CharField(blank=True, default='', help_text='The name of the item.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='associate',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_associate_abstract_thing_owner_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='associate',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='customer',
            name='alternate_name',
            field=models.CharField(blank=True, help_text='An alias for the item.', max_length=255, null=True, verbose_name='Alternate Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A short description of the item.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='', help_text='The name of the item.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user whom owns this thing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_customer_abstract_thing_owner_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the item.', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
