# Generated by Django 2.0.2 on 2018-03-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20180318_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateField(blank=True, help_text='The date the staff member joined this organization.', null=True, verbose_name='Join Date'),
        ),
    ]
