# Generated by Django 2.0.4 on 2018-04-13 04:05

from django.db import migrations, models
import tenant_foundation.models.staff


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20180413_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(db_index=True, default=tenant_foundation.models.staff.increment_staff_id_number, editable=False, primary_key=True, serialize=False),
        ),
    ]
