# Generated by Django 2.0 on 2017-12-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_remove_staff_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='ldn_area',
            field=models.CharField(blank=True, help_text='The area in London that this employee lives in.', max_length=31, null=True, verbose_name='London Area'),
        ),
    ]
