# Generated by Django 2.0.2 on 2018-03-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_ok_to_email',
            field=models.BooleanField(default=True, help_text='Indicates whether customer allows being reached by email', verbose_name='Is OK to email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_ok_to_text',
            field=models.BooleanField(default=True, help_text='Indicates whether customer allows being reached by text.', verbose_name='Is OK to text'),
        ),
    ]
