# Generated by Django 2.0.4 on 2018-04-30 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20180430_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysheetitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this activity sheet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_activitysheetitem_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitysheetitem',
            name='has_accepted_job',
            field=models.BooleanField(help_text='Indicates whether associate has accepted or rejected this job offer.', verbose_name='Has Accepted Job'),
        ),
    ]
