# Generated by Django 2.0.4 on 2018-04-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20180421_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='category',
            field=models.ForeignKey(default=1, help_text='The resource category this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_resourceitem_resource_categories', to='tenant_foundation.ResourceCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='icon',
            field=models.CharField(blank=True, db_index=True, help_text='The icon of this resource item.', max_length=31, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='title',
            field=models.CharField(db_index=True, help_text='The title of this resource item.', max_length=63, verbose_name='title'),
        ),
    ]
