# Generated by Django 2.0 on 2018-02-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20180129_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, help_text='The category text of this skill set.', max_length=31, verbose_name='Category')),
                ('sub_category', models.CharField(db_index=True, help_text='The sub-category text of this skill set.', max_length=31, verbose_name='Sub-Category')),
                ('insurance_requirement', models.CharField(db_index=True, help_text='The insurance requirement of this skill set.', max_length=63, verbose_name='Insurance Requirement')),
            ],
            options={
                'verbose_name': 'Skill Set',
                'verbose_name_plural': 'Skill Sets',
                'db_table': 'o55_skill_sets',
                'permissions': (('can_get_skill_sets', 'Can get skill sets'), ('can_get_skill_set', 'Can get skill set'), ('can_post_skill_set', 'Can create skill set'), ('can_put_skill_set', 'Can update skill set'), ('can_delete_skill_set', 'Can delete skill set')),
                'default_permissions': (),
            },
        ),
    ]
