# Generated by Django 2.0 on 2018-01-14 01:06

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20180114_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='CAD', help_text='The service fee that the customer was charged by the associate..', max_digits=10, verbose_name='Service Fee'),
        ),
    ]
