# Generated by Django 2.0.2 on 2018-03-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20180318_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='birthdate',
            field=models.DateField(blank=True, help_text='The staff members birthdate.', null=True, verbose_name='Birthdate'),
        ),
    ]
