# Generated by Django 2.0.4 on 2018-05-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_associate_away_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='was_postponed',
            field=models.BooleanField(default=False, help_text='Was this task postponed?', verbose_name='Was postponed'),
        ),
    ]
