# Generated by Django 2.0.4 on 2018-05-11 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_awaylog_was_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaylog',
            name='associate',
            field=models.ForeignKey(help_text='The associate of our away log.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_awaylog_associate_related', to='tenant_foundation.Associate'),
        ),
        migrations.AlterField(
            model_name='awaylog',
            name='was_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Track whether this away log was deleted or not.', verbose_name='Was deleted'),
        ),
    ]
