# Generated by Django 2.0.4 on 2018-04-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_customer_skill_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='skill_sets',
            field=models.ManyToManyField(blank=True, help_text='The skill sets this staff has.', related_name='tenant_foundation_staff_skill_sets_related', to='tenant_foundation.SkillSet'),
        ),
    ]
