# Generated by Django 2.0 on 2017-12-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_auto_20171226_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='limit_special',
            field=models.CharField(blank=True, help_text='Any special limitations / handicaps this employee has.', max_length=127, null=True, verbose_name='Limit Special'),
        ),
    ]
