# Generated by Django 2.0.3 on 2018-04-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0003_order_is_home_support_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A description of this job.', null=True, verbose_name='Description'),
        ),
    ]
