# Generated by Django 2.0 on 2017-12-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_auto_20171230_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='learn_about',
        ),
        migrations.AddField(
            model_name='customer',
            name='how_hear',
            field=models.CharField(blank=True, help_text='How customer heared about this organization.', max_length=2055, null=True, verbose_name='How hear'),
        ),
        migrations.AddField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(blank=True, help_text='The date the customer joined this organization.', null=True, verbose_name='Join Date'),
        ),
    ]
