# Generated by Django 2.0.4 on 2018-05-01 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_auto_20180430_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysheetitem',
            name='associate',
            field=models.ForeignKey(help_text='The associate with this activity sheet item.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_activitysheetitem_associate_related', to='tenant_foundation.Associate'),
        ),
        migrations.AlterField(
            model_name='activitysheetitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this activity sheet item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_activitysheetitem_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitysheetitem',
            name='order',
            field=models.ForeignKey(help_text='The order associated with thie activity sheet item.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_activitysheetitem_orders_related', to='tenant_foundation.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='activity_sheet',
            field=models.ManyToManyField(blank=True, help_text='The activity sheet items related to the associates who accepted or rejected this order.', related_name='activity_sheet_set', through='tenant_foundation.ActivitySheetItem', to='tenant_foundation.Associate'),
        ),
    ]
