# Generated by Django 2.0 on 2018-01-14 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_auto_20180114_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='associate',
            field=models.ForeignKey(blank=True, help_text='The associate of our order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_order_associate_related', to='tenant_foundation.Associate'),
        ),
    ]
