# Generated by Django 2.0 on 2017-12-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_auto_20171226_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='drivers_license_class',
            field=models.CharField(blank=True, help_text='The employees license class for driving.', max_length=7, null=True, verbose_name='Divers License Class'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='limit_special',
            field=models.CharField(blank=True, help_text='Any special limitations / handicaps this employee has.', max_length=255, null=True, verbose_name='Limit Special'),
        ),
    ]
