# Generated by Django 2.0 on 2018-02-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_skillset'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='skill_sets',
            field=models.ManyToManyField(blank=True, help_text='The skill sets this associate has.', related_name='tenant_foundation_associate_skill_sets_related', to='tenant_foundation.SkillSet'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='birthdate',
            field=models.DateTimeField(blank=True, help_text='The associates birthdate.', null=True, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='business',
            field=models.CharField(blank=True, help_text='The associates business status.', max_length=63, null=True, verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='comments',
            field=models.CharField(blank=True, help_text='The comments associated with this associate.', max_length=1027, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='drivers_license_class',
            field=models.CharField(blank=True, help_text='The associates license class for driving.', max_length=7, null=True, verbose_name='Divers License Class'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='given_name',
            field=models.CharField(blank=True, help_text='The associates given name.', max_length=63, null=True, verbose_name='Given Name'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='has_car',
            field=models.BooleanField(default=False, help_text='Indicates whether associate has a car or not.', verbose_name='Has Car'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='has_truck',
            field=models.BooleanField(default=False, help_text='Indicates whether associate has a truck or not.', verbose_name='Has Truck'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='has_van',
            field=models.BooleanField(default=False, help_text='Indicates whether associate has a van or not.', verbose_name='Has Van'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='hourly_salary_desired',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The hourly salary rate the associate', null=True, verbose_name='Hourly Salary Desired'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='how_hear',
            field=models.CharField(blank=True, help_text='How associate heared about this business.', max_length=2055, null=True, verbose_name='How hear'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='is_contract_time',
            field=models.BooleanField(default=False, help_text='Indicates whether associate is contracted or not.', verbose_name='Is Contract Time'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='is_full_time',
            field=models.BooleanField(default=False, help_text='Indicates whether associate is full time or not.', verbose_name='Is Full Time'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='is_part_time',
            field=models.BooleanField(default=False, help_text='Indicates whether associate is part time or not.', verbose_name='Is Part Time'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='is_small_job',
            field=models.BooleanField(default=False, help_text='Indicates whether associate is employed for small jobs or not.', verbose_name='Is Small Job'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='join_date',
            field=models.DateTimeField(blank=True, help_text='The date the associate joined.', null=True, verbose_name='Join Date'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='last_name',
            field=models.CharField(blank=True, help_text='The associates last name.', max_length=63, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='limit_special',
            field=models.CharField(blank=True, help_text='Any special limitations / handicaps this associate has.', max_length=255, null=True, verbose_name='Limit Special'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='middle_name',
            field=models.CharField(blank=True, help_text='The associates last name.', max_length=63, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='police_check',
            field=models.DateTimeField(blank=True, help_text='The date the associate took a police check.', null=True, verbose_name='Police Check'),
        ),
    ]
