# Generated by Django 2.0.4 on 2018-05-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_taskitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='text',
        ),
        migrations.AddField(
            model_name='taskitem',
            name='title',
            field=models.CharField(db_index=True, default=1, help_text='The title this task item.', max_length=31, unique=True, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A short description of this task item.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Assign associate'), (2, 'Follow up is job complete'), (3, 'Follow up customer survey')], help_text='The type of task item this is.', verbose_name='Type of'),
        ),
    ]
