# Generated by Django 2.0.2 on 2018-03-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_auto_20180311_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(blank=True, help_text='The customers birthdate.', null=True, verbose_name='Birthdate'),
        ),
    ]
