# Generated by Django 2.0.4 on 2018-04-27 18:32

from django.db import migrations, models
import django.db.models.deletion
import tenant_foundation.models.associate_comment


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_auto_20180427_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateComment',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.associate_comment.increment_associate_comment_id_number, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('about', models.ForeignKey(help_text='The associate whom this comment is about.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_associatecomment_about_related', to='tenant_foundation.Associate')),
                ('comment', models.ForeignKey(help_text='The comment this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_associatecomment_comment_categories', to='tenant_foundation.Comment')),
            ],
            options={
                'verbose_name': 'Associate Comment',
                'verbose_name_plural': 'Associate Comments',
                'db_table': 'o55_associate_comments',
                'ordering': ('-created_at',),
                'permissions': (('can_get_associate_comments', 'Can get associate comments'), ('can_get_associate_comment', 'Can get associate comment'), ('can_post_associate_comment', 'Can create associate comment'), ('can_put_associate_comment', 'Can update associate comment'), ('can_delete_associate_comment', 'Can delete associate comment')),
                'default_permissions': (),
            },
        ),
    ]
