# Generated by Django 2.0.4 on 2018-05-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0004_taskitem_was_postponed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='closing_reason',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The reason for this task was closed.', null=True, verbose_name='Closing Reason'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='closing_reason_other',
            field=models.CharField(blank=True, default='', help_text='A specific reason this task was closed.', max_length=1024, null=True, verbose_name='Closing Reason other'),
        ),
    ]
