# Generated by Django 2.0.4 on 2018-04-27 18:34

from django.db import migrations, models
import django.db.models.deletion
import tenant_foundation.models.staff_comment


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0005_associatecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffComment',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.staff_comment.increment_staff_comment_id_number, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('about', models.ForeignKey(help_text='The staff whom this comment is about.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_staffcomment_about_related', to='tenant_foundation.Staff')),
                ('comment', models.ForeignKey(help_text='The comment this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_staffcomment_comment_categories', to='tenant_foundation.Comment')),
            ],
            options={
                'verbose_name': 'Staff Comment',
                'verbose_name_plural': 'Staff Comments',
                'db_table': 'o55_staff_comments',
                'ordering': ('-created_at',),
                'permissions': (('can_get_staff_comments', 'Can get staff comments'), ('can_get_staff_comment', 'Can get staff comment'), ('can_post_staff_comment', 'Can create staff comment'), ('can_put_staff_comment', 'Can update staff comment'), ('can_delete_staff_comment', 'Can delete staff comment')),
                'default_permissions': (),
            },
        ),
    ]
