# Generated by Django 2.0 on 2017-12-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0005_auto_20171226_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='how_hear',
            field=models.CharField(blank=True, help_text='How employee heared about this business.', max_length=2055, null=True, verbose_name='How hear'),
        ),
    ]
