# Generated by Django 2.0 on 2018-01-16 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_auto_20180116_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user whom owns this comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_comment_owner_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
