# Generated by Django 2.0.4 on 2018-04-27 18:35

from django.db import migrations, models
import django.db.models.deletion
import tenant_foundation.models.order_comment


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_staffcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.order_comment.increment_order_comment_id_number, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('about', models.ForeignKey(help_text='The order whom this comment is about.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_ordercomment_about_related', to='tenant_foundation.Order')),
                ('comment', models.ForeignKey(help_text='The comment this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_ordercomment_comment_categories', to='tenant_foundation.Comment')),
            ],
            options={
                'verbose_name': 'Order Comment',
                'verbose_name_plural': 'Order Comments',
                'db_table': 'o55_order_comments',
                'ordering': ('-created_at',),
                'permissions': (('can_get_order_comments', 'Can get order comments'), ('can_get_order_comment', 'Can get order comment'), ('can_post_order_comment', 'Can create order comment'), ('can_put_order_comment', 'Can update order comment'), ('can_delete_order_comment', 'Can delete order comment')),
                'default_permissions': (),
            },
        ),
    ]
