# Generated by Django 2.0 on 2018-02-04 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
        ('tenant_foundation', '0006_auto_20180204_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_associate_created_by_related', to='shared_foundation.O55User'),
        ),
        migrations.AddField(
            model_name='associate',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_associate_last_modified_by_related', to='shared_foundation.O55User'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_customer_created_by_related', to='shared_foundation.O55User'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom modified this object last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_customer_last_modified_by_related', to='shared_foundation.O55User'),
        ),
    ]
