# Generated by Django 2.0.4 on 2018-05-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0006_auto_20180505_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='title',
            field=models.CharField(help_text='The title this task item.', max_length=63, verbose_name='Title'),
        ),
    ]
