# Generated by Django 2.0 on 2017-12-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='given_name',
            field=models.CharField(blank=True, help_text='The employees given name.', max_length=63, null=True, verbose_name='Given Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, help_text='The employees last name.', max_length=63, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, help_text='The employees last name.', max_length=63, null=True, verbose_name='Middle Name'),
        ),
    ]
