# Generated by Django 2.0.4 on 2018-05-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0008_auto_20180505_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskitem',
            options={'default_permissions': (), 'ordering': ['due_date'], 'permissions': (('can_get_task_items', 'Can get task_items'), ('can_get_task_item', 'Can get task_item'), ('can_post_task_item', 'Can create task_item'), ('can_put_task_item', 'Can update task_item'), ('can_delete_task_item', 'Can delete task_item')), 'verbose_name': 'TaskItem', 'verbose_name_plural': 'TaskItems'},
        ),
    ]
