# Generated by Django 2.0.4 on 2018-04-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0009_auto_20180427_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=1, help_text='The text content of this comment.', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
