# Generated by Django 2.0.4 on 2018-05-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0009_auto_20180506_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysheetitem',
            name='order',
        ),
        migrations.AddField(
            model_name='activitysheetitem',
            name='job',
            field=models.ForeignKey(default=1, help_text='The job associated with thie activity sheet item.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_activitysheetitem_jobs_related', to='tenant_foundation.Order'),
            preserve_default=False,
        ),
    ]
