# Generated by Django 2.0 on 2018-02-04 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0010_customercomment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user whom owns this comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_comment_created_by_related', to='shared_foundation.O55User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user whom last modified this comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_foundation_comment_last_modified_by_related', to='shared_foundation.O55User'),
        ),
    ]
