# Generated by Django 2.0.4 on 2018-04-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0010_auto_20180427_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercomment',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': (('can_get_customer_comments', 'Can get customer comments'), ('can_get_customer_comment', 'Can get customer comment'), ('can_post_customer_comment', 'Can create customer comment'), ('can_put_customer_comment', 'Can update customer comment'), ('can_delete_customer_comment', 'Can delete customer comment')), 'verbose_name': 'Customer Comment', 'verbose_name_plural': 'Customer Comments'},
        ),
    ]
