# Generated by Django 2.0.4 on 2018-05-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0011_auto_20180506_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='score',
            field=models.FloatField(blank=True, default=0, help_text='The score with this associated.', verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='order',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The score number earned at the completion of this date.', verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='order',
            name='was_associate_professional',
            field=models.BooleanField(default=True, help_text='Customer Survey Q4: Was the Associate Member professional?', verbose_name='Was associate professional?'),
        ),
        migrations.AddField(
            model_name='order',
            name='was_associate_punctual',
            field=models.BooleanField(default=True, help_text='Customer Survey Q3: Was the Associate Member punctual?', verbose_name='Was associate punctual?'),
        ),
        migrations.AddField(
            model_name='order',
            name='was_job_finished_on_time_and_on_budget',
            field=models.BooleanField(default=True, help_text='Customer Survey Q2: Was the work completed on time and on budget?', verbose_name='Was job finished on time and on budget?'),
        ),
        migrations.AddField(
            model_name='order',
            name='was_job_satisfactory',
            field=models.BooleanField(default=True, help_text='Customer Survey Q1: Was the quality of the work satisfactory?', verbose_name='Was job satisfactory?'),
        ),
        migrations.AddField(
            model_name='order',
            name='would_customer_refer_our_organization',
            field=models.BooleanField(default=True, help_text='Customer Survey Q5: Would you refer Over55 to a friend of family member?', verbose_name='Would customer refer our organization?'),
        ),
    ]
