# Generated by Django 2.0 on 2018-02-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
        ('tenant_foundation', '0011_auto_20180204_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('associate', models.ForeignKey(help_text='The associate of our reference.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_associatecomment_associate_related', to='tenant_foundation.Associate')),
                ('comment', models.ForeignKey(help_text='The comment of our reference.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_associatecomment_comment_related', to='tenant_foundation.Comment')),
                ('created_by', models.ForeignKey(help_text='The user whom created this object.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_associatecomment_created_by_related', to='shared_foundation.O55User')),
            ],
            options={
                'verbose_name': 'Associate Comment',
                'verbose_name_plural': 'Associate Comments',
                'db_table': 'o55_associate_comments',
                'ordering': ('-created_at',),
                'permissions': (('can_get_associate_comments', 'Can get associate comments'), ('can_get_associate_comment', 'Can get associate comment'), ('can_post_associate_comment', 'Can post associate comment'), ('can_put_associate_comment', 'Can update associate comment'), ('can_delete_associate_comment', 'Can delete associate comment')),
                'default_permissions': (),
            },
        ),
    ]
