# Generated by Django 2.0.4 on 2018-04-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0011_auto_20180427_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': (('can_get_comments', 'Can get comments'), ('can_get_comment', 'Can get comment'), ('can_post_comment', 'Can create comment'), ('can_put_comment', 'Can update comment'), ('can_delete_comment', 'Can delete comment')), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
