# Generated by Django 2.0.4 on 2018-04-28 00:31

from django.db import migrations, models
import django.db.models.deletion
import tenant_foundation.models.partner_comment


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0012_auto_20180427_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerComment',
            fields=[
                ('id', models.BigAutoField(db_index=True, default=tenant_foundation.models.partner_comment.increment_partner_comment_id_number, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('about', models.ForeignKey(help_text='The partner whom this comment is about.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_partnercomment_about_related', to='tenant_foundation.Partner')),
                ('comment', models.ForeignKey(help_text='The comment this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_partnercomment_comment_categories', to='tenant_foundation.Comment')),
            ],
            options={
                'verbose_name': 'Partner Comment',
                'verbose_name_plural': 'Partner Comments',
                'db_table': 'o55_partner_comments',
                'ordering': ['-created_at'],
                'permissions': (('can_get_partner_comments', 'Can get partner comments'), ('can_get_partner_comment', 'Can get partner comment'), ('can_post_partner_comment', 'Can create partner comment'), ('can_put_partner_comment', 'Can update partner comment'), ('can_delete_partner_comment', 'Can delete partner comment')),
                'default_permissions': (),
            },
        ),
    ]
