# Generated by Django 2.0 on 2018-02-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0012_associatecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='comments',
        ),
        migrations.AddField(
            model_name='order',
            name='skill_sets',
            field=models.ManyToManyField(blank=True, help_text='The skill sets that belong to this order.', related_name='tenant_foundation_order_skill_sets_related', to='tenant_foundation.SkillSet'),
        ),
    ]
