# Generated by Django 2.0.4 on 2018-04-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0013_partnercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='comments',
            field=models.ManyToManyField(blank=True, help_text='The comments belonging to this partner made by other people.', related_name='tenant_foundation_partner_partner_comments_related', through='tenant_foundation.PartnerComment', to='tenant_foundation.Comment'),
        ),
    ]
