# Generated by Django 2.0 on 2018-02-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0013_auto_20180204_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='comments',
            field=models.ManyToManyField(blank=True, help_text='The comments of this associate sorted by latest creation date..', related_name='tenant_foundation_associate_associate_related', through='tenant_foundation.AssociateComment', to='tenant_foundation.Comment'),
        ),
    ]
