# Generated by Django 2.0.4 on 2018-04-28 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0014_partner_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associatecomment',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': (('can_get_associate_comments', 'Can get associate comments'), ('can_get_associate_comment', 'Can get associate comment'), ('can_post_associate_comment', 'Can create associate comment'), ('can_put_associate_comment', 'Can update associate comment'), ('can_delete_associate_comment', 'Can delete associate comment')), 'verbose_name': 'Associate Comment', 'verbose_name_plural': 'Associate Comments'},
        ),
        migrations.AlterModelOptions(
            name='ordercomment',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': (('can_get_order_comments', 'Can get order comments'), ('can_get_order_comment', 'Can get order comment'), ('can_post_order_comment', 'Can create order comment'), ('can_put_order_comment', 'Can update order comment'), ('can_delete_order_comment', 'Can delete order comment')), 'verbose_name': 'Order Comment', 'verbose_name_plural': 'Order Comments'},
        ),
        migrations.AlterModelOptions(
            name='staffcomment',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': (('can_get_staff_comments', 'Can get staff comments'), ('can_get_staff_comment', 'Can get staff comment'), ('can_post_staff_comment', 'Can create staff comment'), ('can_put_staff_comment', 'Can update staff comment'), ('can_delete_staff_comment', 'Can delete staff comment')), 'verbose_name': 'Staff Comment', 'verbose_name_plural': 'Staff Comments'},
        ),
    ]
