# Generated by Django 2.0 on 2018-02-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0014_associate_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associatecomment',
            name='created_by',
        ),
    ]
